apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: envoy-gateway-system
  labels:
    extension.tetrate.io/kong-config: "true"
    app: envoy-extproc
data:
  config: |+
    kong.yaml: |+
      _format_version: "3.0"
      _transform: true
      services:
      - name: example
        url: http://www.example.com
        routes:
        - name: my-route-0
          paths:
          - /
          plugins:
          - name: request-transformer
            config:
              add:
                headers:
                - "x-kong-request-header-1:foo"
                - "x-kong-request-header-2:bar"
          - name: response-transformer
            config:
              add:
                headers:
                - "x-kong-response-header-1:foo"
                - "x-kong-response-header-2:bar"
