apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: kong2envoy
    extension.tetrate.io/kong-config: "true"
  name: kong-config
  namespace: envoy-gateway-system
data:
  config: |
    plugins:
    - name: my-custom-plugin
      configMapName: custom-kong-plugin
    kong.yaml: |+
      _format_version: "3.0"
      _transform: true
      services:
      - name: receiver
        url: http://localhost:16002
        routes:
        - name: no-op-route # The fallback route for Kong to handle unmatched requests
          paths:
          - /
        - name: my-route-0
          hosts:
          - www.example.com:10080
          paths:
          - /
          plugins:
          - name: my-custom-plugin
            config:
              message: "Hello from my custom plugin!"
          - name: request-transformer
            config:
              add:
                headers:
                - "x-kong-request-header-1:foo"
                - "x-kong-request-header-2:bar"
